services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # or your frontend port
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # or your backend port
    environment:
      - MONGO_URI=mongodb://172.31.81.30:27017/contacts
#here host.docker.inter refers tothe host machine itself
#It is an alternative to localhost so we can directly access service on the host machine(mongo in our case)