name: Terraform Deploy

on:
  workflow_dispatch:     # Enables manual triggering from GitHub UI
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest  # Use a Linux runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.3  # Specify the version you're using

      # Step 3: Configure AWS credentials (from GitHub Secrets)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_DEFAULT_REGION }}  # Optional: If not already in main.tf

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Plan (review changes)
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Step 6: Terraform Apply (apply the plan automatically)
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
